# Generated by Django 4.1.3 on 2023-12-11 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0005_rename_genre_id_songgenre_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='song_genres', to='tunaapi.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunaapi.artist'),
        ),
        migrations.DeleteModel(
            name='SongGenre',
        ),
    ]
