# Generated by Django 4.1.3 on 2023-12-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0006_song_genres_alter_song_artist_delete_songgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='tunaapi.artist'),
        ),
    ]
